version: 0.2
env:
  variables:
    GOOS: "darwin"
  parameter-store:
    GOOS: "/codebuild-nht/goos"
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - echo $GOOS
      - make -f ./lab_01/Makefile
artifacts:
  files:
    - '**/*'
