version: 0.2
env:
  variables:
    GOOS: "darwin"
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - mkdir lab_01/out
      - ./lab_01/script
artifacts:
  files:
    - '**/*'
  base-directory: lab_01
